version: '2'

networks:
  poc:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./:/jenkins
    
  sonar_qube:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
    networks:
      - poc
    volumes:
    - ./:/sonar_qube
    depends_on:
    - postgresql
  postgresql:
    image: orchardup/postgresql
    ports:
    - 5432:5432
    networks:
      - poc
    environment:
      - POSTGRESQL_USER=sonar
      - POSTGRESQL_PASS=sonar
      - POSTGRESQL_DB=sonar
    networks:
      - poc
    volumes:
    - ./:/postsgresql